### ISSUE TITLE
Info & Help popup placement should be reversed in rtl mode?

### ISSUE THREAD

**Issue by faraazandeh** [michael-milette/moodle-filter_filtercodes#153] opened 2021-04-04 17:04 UTC
Hello there,
Thanks again for your very useful plug-in. I wanted to create some help & info content for moodle blocks & this happened:
When using rtl mode, the popup bubble should be mirrored, but it is not, so the bubble's V is kinda directing to the blank space as in the picture below. I tried changing the data placement from inspector but couldn't find a fix using custom css.
Can you please help solve this issue?

p.s. is there anyway to add this {info} content to block names while customizing the language? Or another way to put it into blocks where you don't have a space to place any text?

Sincere Regards 🙌🏻

![IMG_20210404_214237_202.jpg](https://user-images.githubusercontent.com/63648409/113516298-b769f000-958e-11eb-8b9b-3a0bb054fef9.jpg)

**Comment by michael-milette** [comment] 2021-04-04 17:39
Hi @faraazandeh ,

I dont have experience with RTL. If you could find me the HTML for an RTL popup box, I might be able to fix the problem for you.

As for adding it to block names, there is a bit of a problem there. Moodle currently filters out all HTML in a block name so, while Filtercodes tries to add in the HTML as expected, the block code filters it out. I have a tracker ticket to fix this but so far, it is not moving along very quickly. For more information, see:

"[#MDL-66856] Allow HTML in Custom Menu - Moodle Tracker" https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-66856

Best regards,

Michael

**Comment by faraazandeh** [comment] 2021-04-04 18:19
Dear @michael-milette is there anyway to change the placement from right to bottom so it works both ways?

About the tracker yeah I voted for it before as you mentioned it under one of your plugins, Thanks!

**Comment by michael-milette** [comment] 2021-04-04 20:13
I can only make it look the way it usually does in an RTL environment. I think the bubble placement is usually automatic depending on where there is enough room for it to appear (but I did not test that). I would need the HTML code previously requested in order to help me figure it out how to make the bubble work the way it does everywhere else in Moodle..

**Comment by faraazandeh** [comment] 2021-04-06 23:25
Dear @michael-milette
I found this link, regarding the same issue, hope it can be of any help.

https://stackoverflow.com/questions/31932992/display-bootstrap-popover-with-right-to-left-languages


Sincere Regards

**Comment by faraazandeh** [comment] 2021-04-20 21:22
Dear @michael-milette
I found this link, regarding the same issue, hope it can be of any help.

https://stackoverflow.com/questions/31932992/display-bootstrap-popover-with-right-to-left-languages


Sincere Regards 🙌🏻

**Comment by michael-milette** [comment] 2021-04-29 05:13
Hi @faraazandeh ,

I took a look at your issue today. While I was easy to reproduce, I noticed that the problem also happened with bubbles which are part of Moodle core. In particular, I looked at the Edit Course Settings page for one of my courses. This means that it is actually Moodle core themes issue, not an issue with FilterCodes.

I recommend that you go to https://tracker.moodle.org and report the issue in a ticket. I would not mention FilterCodes (because it is not part of Moodle core) but demonstrate that the issue happens with all help bubbles for Moodle core pages such as when editing course settings in Arabic (haven't tried other RTL languages).

Feel free to include the link you mentioned above and any other information which might help someone to troubleshoot and fix the issue with RTL languages.

Once the issue has been fixed in Moodle core, I suspect that it will likely be fixed for FilterCodes as well. If it doesn't address the issue after Moodle has been fixed, feel free to re-open this ticket and I will continue to look into it.

Best regards,

Michael

**Closed by michael-milette** 2021-04-29 05:13 UTC
