### ISSUE TITLE
Using filters in URL parameters?

### ISSUE THREAD

**Issue by argwallace** [michael-milette/moodle-filter_filtercodes#105] opened 2020-05-23 12:38 UTC
Hello!

I have been testing the FilterCodes plugin and it's great! I have been able to add a filtercode to text with no issues and also menus. When I tried to have a URL parameter in a settings use an {{ifloggedin}} so I could have two options for a URL, it came back as an invalid URL. I am assuming this is an internal Moodle check (PARAM_URL). But just wanted to mention it in case there was some sort of workaround.

Thanks!

**Comment by michael-milette** [comment] 2020-05-23 16:10
Hi @argwallace ,

Thank you for your question. I might be able to help you with that. However I will need to have a clearer understanding of what you are trying to do.

Could you please provide the details of a specific use case so that I could determine exactly what your issue is and whether or not the solution I have in mind will help?

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-23 17:42
Hey!

Sure! In a theme that I am using, I have a call to action button that contains a URL. I am able to change the text of the button via FilterCodes but when I want to have the URL change based on logged in status, the URL doesn’t pass validation.

That’s the main use case for me, being able to alter the URL links based on the logged in or not status.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 03:58
Hi Stephen,
Have you considered something like this:

    <a href="https://yourMoodleURL.org/do-the-thing.php?param={ifloggedin}1{/ifloggedin}{ifloggedout}0{/ifloggedout}" class="btn btn-primary">Do the thing</a>

Alternatively...

     {ifloggedin}
         <a href="https://yourMoodleURL.org/do-the-thing.php?param=1" class="btn btn-primary">Do the thing</a>
     {/ifloggedin}
     {ifloggedout}
         <a href="https://yourMoodleURL.org/do-the-thing.php?param=0" class="btn btn-primary">Do the thing</a>
     {/ifloggedout}

When the page renders for the user, the URL of the link should be correct and the tags removed. If they are being passed, then then there is something in your theme that is being passed through the Moodle filters before it is sent to the web browser.

Am I misunderstanding your case? If so, perhaps I need a little more detail so that I can reproduce your situation

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-24 04:10
Thanks. My fault. I should have given you more info. 

The issue isn’t with doing this in the HTML but via the Settings of the theme where I just have a field to enter a URL. My guess is the theme settings are being saved and flagged for not being a valid URL and thus kicked back. 

Does that make sense?

Stephen

**Comment by michael-milette** [comment] 2020-05-24 04:41
Hi Stephen,

Here is the problem. Moodle filters are designed to work when it outputs content. While I could give you a fix that would pass the URL validation test, it would not help you because the receiving end would just end up with encoded versions of the tags.

Question 1: Can you clarify whether you are indeed able to save the URL with the {ifloggedin} tags in it? This is regardless of whether it submits it or not at this point.

If it does not, try adding **%7Buserid%7D** to your URL instead. You should be able to save the URL.

Next, check what comes out from the theme. If the URL still includes **%7Buserid%7D**, then the field is not being passed through the Moodle filters and you will need to have the developer of the theme fix that. You may even be able to explain what you are attempting to do and have him lift the validation of the URL. On the other hand, if it does get converted to a number, great! Continue on.

My suspicion is that you may need to contact the developer. Most of the time, they don't pass URLs through Moodle filters so I suspect that this will be your case. 

In order to make things work for you, you must first get %7Buserid%7D to turn into a number. If you can't, there is nothing that I will be able to do for you in this regards as far as FilterCodes is concerned.

If it is any consolation, I had to go through a very similar exercise recently in order to get Moodle to pass a language parameter to a single-sign-on system so that it would come up in the right language (multi-language site). But instead of just a theme, it took several months to push a patch through Moodle HQ to modify core Moodle code. Hopefully things will work out quicker for you.

Please let me know how it all turns out.

Best regards,

Michael

**Comment by michael-milette** [comment] 2020-05-24 04:42
By the way, which theme are you using and which setting field are you trying to do this with? (if you don't mind my asking)

**Comment by argwallace** [comment] 2020-05-24 05:35
Michael,

I have tested and here are the results:

1. I am not able to get the filter codes to work in the URL parameter via the settings. It does work though if in the same settings area of the theme for a text editor.

I added the %7Buserid%7D and it did accept this into the URL but it didn’t resolve anything based on it.

I have not reached out to the developer but I did add the code into the theme manually per the instructions for the plugin. I have noticed that the code for the theme uses a “PARAM_URL” flag. So my guess that this is where the validation is happening.

The area in question has button text and the button URL. On the button text, the filtercode works just fine. On the URL, it does not. So parts are working with the theme.

I appreciate your work.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 08:39
Hi Stephen,

You are correct regarding PARAM_URL. All of the PARAM_XXXX flags are defined at the beginning of the /lib/moodlelib.php file. Your goal would be to choose the one that is the most restrictive while still allowing you to enter the URL.

The fact that %7Buserid%7D did not get resolved tells me that the theme does not process the URL through Moodle filters. You would need to find the part of the code where the URL is generated or output and have it go through the format_text( ) or format_string( ) functions. You can find more information on this by going to https://docs.moodle.org/dev/Output_functions . That documentation isn't great. You would probably find better examples of how to use these functions by searching through the Moodle source code.

Once you resolve these two issues in your theme, you will find that FilterCode tags work just fine without any need for modifications to it.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-24 08:46
Thank you for this info. I will look into this further  Also, Does this mean that the mods I added to the theme via the documentation for developers on how to add filter codes to the theme was done incorrectly? I’m referring to the changes in the core renderer file.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 16:45
It is not that it was done incorrectly. It is just that it serves a different purpose which is to enable FilterCodes in the Custom Menu. 

With that enabled, you can have a menu appear just for Administrators, Managers or Teachers. My clients love when I add the most popular features in this menu to a website. It saves them from having to navigate through the Site Administration menu.

To see examples of custom menus, go to https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/README.md#filtercodes-in-a-custom-menu

Since I created those custom menus, I have developed even more advanced versions of these menus which are language and context aware. For example, if you are in a course, you will have the option of backing up the course right from my custom Admin menu. Another cool use is to add the new {categories0menu} tag to the menu which will create a dropdown of all visible top level categories.

**Comment by michael-milette** [comment] 2020-05-26 04:52
Hi Stephen,

As the changes need to be made in the theme and not in FilterCodes in order to achieve the results you are after, I will close this issue for now. Please feel free to contact me for further assistance with the theme.

Should any additional information come up with regards to this issue and FilterCodes, feel free to re-open the issue.

Best regards,

Michael

**Closed by michael-milette** 2020-05-26 04:52 UTC
Labels: question
