### ISSUE TITLE
Bug: FilterCodes FontAwesome conflict with Activity name auto linking (core)

### ISSUE THREAD

**Issue by joostelshoff** [michael-milette/moodle-filter_filtercodes#248] opened 2023-01-10 14:21 UTC
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [ ] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

When using a {fa fa-clock-o fa-lg} code (or any of the FontAwesome icons with a -o addition), the filter breaks these into unreadable HTML if you use activity names auto linking filter in addition to the FilterCodes filter.

### What do you think should have happened?

All FontAwesome icons should be displayed properly, regardless if they contain the -o suffix like fa fa-clock-o

### Steps to reproduce

1. Login as '...' (specify user role)
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error or issue.
You get it?

### Screenshots

Create a course
Create a label containing the {fa fa-clock-o fa-lg} icon code and save
Enable FilterCodes filter in the course and check to see if the code converts to the correct icon
Enable Activity name auto linking filter in the course and check to see if the code is now broken

### Moodle version

Moodle 3.11

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

NL, ES, DE, FR

### Workaround

Use <nolink></nolink> tags around the affected icons. This is quite labour intensive, though.

### System information

Client Device type: Laptop
Client Operating System: Windows 11, Mac OS Ventura
Client Web Browser: Edge, Firefox for Mac
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.3, 7.4, 8.x, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment] 2023-01-11 16:18
Hi @joostelshoff ,

Thank you for reporting this issue. I will definitely look into this and get back to you.

Best regards,

Michael

**Comment by michael-milette** [comment] 2023-05-17 19:56
Hi @joostelshoff ,

I followed your instructions on multiple versions of Moodle 3.x and 4.x including 3.11. There must be more to your instructions because I am unable to reproduce the issue you are experiencing.

<img width="106" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/8548134e-7a09-4b2c-83c0-f61a47728ee1">

Best regards,

Michael Milette

**Comment by michael-milette** [comment] 2023-07-30 18:21
There has been no further response to the request for additional details in this ticket for over 2 months. I am therefore closing it for now. If you would like to resume working on it with me, please feel free to re-open the issue ticket.

Best regards,

Michael

**Closed by michael-milette** 2023-07-30 18:21 UTC
Labels: question to participant
