### ISSUE TITLE
Custom Profile Field with value of 0 shows nth instead of 0

### ISSUE THREAD

**Issue by faraazandeh** [michael-milette/moodle-filter_filtercodes#149] opened 2021-03-16 00:00 UTC
**Moodle 3.10**
We set a custom profile field for Credit with the default value of 0. When using {profile_field_shortname}, it shows only when the credit is more than 0 & shows nth when it's 0.

**Comment by michael-milette** [comment] 2021-03-16 06:50
Hi @faraazandeh , thank you for reporting this issue.

I believe that I have identified the cause and fixed the problem. However, the fix is currently only included in the version available here on GitHub.

If you have a chance, would you be so kind as to try it out? Let me know if this solves your issue. Your help would be very much appreciated.. 

If it resolves the issue for you, I will include it in the next official release on Moodle.org in May 2021, around the same time as the launch of Moodle 3.11.

While fixing this issue for you, I noticed and fixed another related issue with the same tag. Thanks to your voice and your actions, many Moodle site around the world and people will also benefit.

Thank you so much for finding the courage to speak up.

Best regards,

Michael Milette

**Comment by faraazandeh** [comment] 2021-03-16 20:44
Dear Michael,
Thanks for your kind support,
I updated the plugin to this brand new github version & it seems like that the issue is solved!
Thanks again for your help & dedications to the community.

P.S. There's a new setting for global tags. Can you please help me where to find information about this new setting?

Sincere Regards

**Comment by michael-milette** [comment] 2021-03-17 19:32
Hi @faraazandeh 

You are very welcome.

As for the global tags, see the README.md file. 

A Moodle Administrator can create up to 20 custom tags in the FilterCodes settings for use by course creators/teachers. They allow you to create global blocks. You can define up to 20 tags with static content and place like you would any other FilterCode tag. Moodle then substitutes the tag for your content almost anywhere it is placed.

For example, lets say you want to put your organization's phone number or a support link in every course. You just define it in a global block and then you just need to add the tag wherever you want the information to appear. In the future, if the phone number or email address changes, you just need to make the change in one spot and it will be changed throughout the whole site. Other applications could be business hours (different in the summer?), an HTML or JavaScript code snippets, a link, a copyright, notices, etc.

I am already using it on a Moodle site where I need to use some HTML tags that Moodle's Atto editor filters out. So I put the code in one of these tags, and then just added the tag to my page.

If you need something more powerful, you can take a look at the Generico plugin. However, for simple static content, the FilterCodes Global tags work great.

If you decide to give it a try, I would appreciate it if you would let me know how you use it.

**Comment by luisdev** [comment] 2021-03-18 07:17
Thanks for this Michael. To test this fix do we use the Master branch?

**Comment by faraazandeh** [comment] 2021-03-19 00:28
@michael-milette 

Dear Michael,
Thanks for your thorough explanation.
I respect & appreciate your spirit toward moodle community.

If we get the chance to use global tags [and or] generico plug-in, I'll give you a feedback & let you know how we're implementing it.


Sincere Regards

**Comment by michael-milette** [comment] 2021-03-19 06:09
Hi @luisdev , yes, the master branch.

**Comment by michael-milette** [comment] 2021-05-01 18:58
Hi @faraazandeh ,

I didn't realize this ticket and #151 were both for you.

As it has been over a month since I last heard from you, I will assume that the latest version is meeting your needs and will close this ticket. If it does not, please feel free to re-open this ticket or create a new one.

Best regards,

Michael

**Closed by michael-milette** 2021-05-01 18:58 UTC
Labels: bug, testing required
