### ISSUE TITLE
Bug: Course Participants Count Issue is broken

### ISSUE THREAD

**Issue by argwallace** [michael-milette/moodle-filter_filtercodes#104] opened 2020-05-23 10:34 UTC
Just updated using the recent changes and noticed that there was an issue with the courseparticipantscount function. It throws up an error about not being defined.

**Comment by michael-milette** [comment] 2020-05-23 16:13
Hi @argwallace ,

Could you please tell me where you were using the tag?

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-23 19:45
Hey,

I used this {courseparticipantcount} filter code on a course that I am enrolled in. But I also tried it on one that I am not enrolled. To test, I put it into a Label resource for the course and entered it the filter code there.

I have attached an image of the errors.

Thanks,

Stephen

**Comment by michael-milette** [comment] 2020-05-24 04:06
Hi @argwallace ,

Thank you for reporting this issue. The {courseparticipantcount} is actually brand new and will be included in the next release of Filtercodes a few days before the launch of Moodle 3.9 next month.

I believe that I found the cause of the issue and fixed it. If you would be so kind as to download the updated version directly from Github and try it out, I would really appreciate it if you would let me know if it addressed the issue for you as well.

Thank you again for helping me work out this issue.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-24 04:11
Ok! Great I will test and let you know. 

Best regards,
Stephen

**Comment by argwallace** [comment] 2020-05-24 05:30
Hey,

I just tried the new changes but unfortunately the error persists. I tried purging any of the caches and installed it a second time. But still no change.

Maybe I am doing something wrong??

Stephen

PS - All of the other functions work.

**Comment by michael-milette** [comment] 2020-05-24 17:45
Hi Stephen,

I am not sure why it isn't working for you. This should have fixed it. Could you check a few things for me? (note: Slashes are the other way (\) in Windows)

1. Is there a folder called /filter/moodle-filter_filtercodes ? If so, you need to delete the folder called /filter/filtercodes and rename /filter/moodle-filter_filtercodes to /filter/filtercodes. If that does not fix it, continue on to the next step.

2. Open the file /filter/moodle-filter_filtercodes/filter.php with a text editor and go to line 605. Does the line look like this (including the \ slash right before user)?:
     $cnt = \user_get_total_participants($PAGE->course->id);

If not, you are not using the latest version of FilterCodes from GitHub (adding the backslash was the fix). If it is correct, move on to step 3. 

3. Please tell me which version of Moodle you are using as well as which course format and all of the Course Format settings in the Course Settings. The issue could potentially be related to any of these.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-24 17:53
Michael,

Thanks for your persistence.

I have just the filter/filtercodes folder. So I didn’t need to delete or change that portion.

I do have the text correct in line 501 as can be seen here:



I am using Moodle 3.8.3 on the theme Maker by 3rdwavemedia.com <http://3rdwavemedia.com/>

The course format is “Collapsible Topics”. I could try a different topic perhaps if it seems that is the issue.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 19:23
Hi Stephen,

I am using Moodle 3.8.3 too so that is not the issue.

You could try the Boost theme to see if it makes a difference.

I have not tried the Collapsible Topics course format. As this is not part of Moodle core, it could very well be related to this issue. Give the Topics format a try. It is very possible that this is the cause of the problem.

While you are looking into that, I will track down the Collapsible Format course format and give it a try on my instance of Moodle.

Best regards,

Michael

**Comment by michael-milette** [comment] 2020-05-24 19:25
On a side note, do you make use of dropdown custom menus with Maker? I noticed it has a couple of problems with navigation when using a mouse.

1) If you go to their demo page at https://themes.3rdwavemedia.com/moodle/maker/1/, hover over the **Moodle Themes** menu with your mouse. Then try to move down. The menu disappears. In order to actually be able to select something from the menu, you nee to first click on the top level menu item, **Moodle Themes** in this case, and then click on one of the sub-menu items. Not intuitive. Either have the user click the menu in order for it to be displayed or let me choose something from the sub-menu just by hovering and without the need to click.

2) When you hover over the **Moodle Themes** menu, the sub-menu appears correctly and is fully visible. However, if you click on **Moodle Themes** menu item, the sub-menu background is no longer wide enough and half of each menu item ends up over whatever is behind the menu on the page, 

I am not trying to put down the Maker theme or its developers. It is a very theme with obviously lots of work put into it. However I just thought you might want to get these two issues fixed in case you ever need to make use of them.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-24 19:28
Michael,

It’s funny that you mentioned that. I had just written a note to the developers of the theme for them to look into this issue. They have been responsive on the other minor issues I have already found and which were fixed. Hopefully, this will be the case here too.

That’s the only thing about the theme so far that I have been unpleased with. The rest, it has worked very well.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 19:31
One more observation with the Maker theme. If you click on the **Page** menu, and then move over to the **Moodle Themes** menu and click on that, then move your mouse back and forth hovering it on the **Page** and **Moodle Themes** menu items, menus that should be closed remain open.

**Comment by argwallace** [comment] 2020-05-24 19:33
Here is what I have tried:

- I switched to the Topics format and there was no change.
- I tried the Boost theme, no change, I still get the error.

Not sure what it could be, especially if you have it working on your site.

Stephen

**Comment by michael-milette** [comment] 2020-05-24 19:34
Just to be clear, is it this one that you are using?
https://moodle.org/plugins/format_collapsibletopics

**Comment by argwallace** [comment] 2020-05-24 19:35
Indeed, it is.

**Comment by michael-milette** [comment] 2020-05-24 19:35
Also...

1) How many participants do you have enrolled in the course?
2) Do you still have the problem when logged-in as a Moodle Administrator or just as a Student?

Michael

**Comment by argwallace** [comment] 2020-05-24 19:37
Good questions…

Since this is a test site that we are just now putting together, I am set as the administrator and I am currently enrolled also in the course. Let me try with another course where a student is enrolled.

The number of participants are just one or two in the courses at the moment for testing purposes.

**Comment by michael-milette** [comment] 2020-05-24 19:43
That is fine. I was just wondering if there might be zero students enrolled.

**Comment by michael-milette** [comment] 2020-05-24 19:44
How are the students enrolled?

**Comment by michael-milette** [comment] 2020-05-24 19:44
I tested it with the Collapsible Format and it works fine for me. So that is not it.

**Comment by michael-milette** [comment] 2020-05-24 19:47
Just out of curiosity, can you add the following line in the Summary of the General section of the course and tell me if it works? (edit the settings for the General section)

`{courseparticipantcount} Learners`

**Comment by argwallace** [comment] 2020-05-24 19:52
Success!!

Yes, adding that line in the Summary section of General works. I had been adding just {courseparticipantcount} by itself and in a label to test.

At least, this is progress!!

Stephen

**Comment by michael-milette** [comment] 2020-05-24 19:58
ok, let see where this stops working. Can you now create a new label in your course, in the General section. If you have other modules there, make this the first one. The idea is to move it down the page to see where it stops working and what is right above it.

**Comment by argwallace** [comment] 2020-05-24 20:20
I tried putting it in a label just after Summary and the error returns. If I put it in the Summary, it’s ok. 

Hope that helps.

**Comment by michael-milette** [comment] 2020-05-24 20:30
Is there anything else in your course? Try it with a blank course.

**Comment by michael-milette** [comment] 2020-05-24 20:32
I also tried it with a fresh installation of Moodle 3.9 with nothing but FilterCodes installed. It worked. It has to be something particular to your installation of Moodle

**Comment by michael-milette** [comment] 2020-05-24 20:32
I don't mind working to resolve it but I need to be able to reproduce the issue first.

**Comment by argwallace** [comment] 2020-05-25 07:14
I completely understand!

So here is what I have found so far:

1. If I put the {courseparticipantcount} tag into the Summary on any of the topics, it works just fine.
2. If I add the {courseparticipantcount} tag to activities like File or Page, it also works fine.
3. If I add a Label and put the tag in the label, it causes an error. The order doesn’t matter.

Not sure of that helps.

Stephen

**Comment by michael-milette** [comment] 2020-05-25 14:26
Hi Stephen,

Thanks. Did you try it in a brand-new empty course? Boost theme, Topics course format. Same test.

Also, with regards to the error message, can you either insert that screenshot directly on GitHub or copy and paste it into a message. That attached screenshot you included when you replied through email didn't seem to come through.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-25 15:00
I tried a brand new course with Topics (with my current theme). I will need to test with Boost theme to see if it does the same but the results haven't changed.

If I use the {courseparticipantcount} in any other activity/resource it works fine but when I do so in Label, it does not. I am attaching the error message I get when this happens.

<img width="1155" alt="errors" src="https://user-images.githubusercontent.com/65811524/82824173-853d2b80-9eb1-11ea-97c8-cdcb2dc9fc5e.png">

**Comment by michael-milette** [comment] 2020-05-25 15:20
Thanks. I have other (paid) work I need to focus on right now. I will look for a solution and get back to you with possibly more trials.

**Comment by argwallace** [comment] 2020-05-25 15:21
No problem! I will continue to test on my end and pass along new info as I have it.

**Comment by michael-milette** [comment] 2020-05-27 04:02
Hi Stephen,

A new version of FilterCodes is now available on GitHub. It just might do the trick. Please try the {courseparticipantcount} out on both your simplest course and a course that makes use of most varied assortment of activity types if you can. Please let me know how it goes.

Best regards,

Michael

**Comment by argwallace** [comment] 2020-05-27 07:23
Michael,

I will continue to test further but at first glance it seems to be WORKING!

Thanks for your work and I will test more.

Bets regards,

Stephen

**Comment by michael-milette** [comment] 2020-05-27 17:23
Thanks for the update Stephen! Glad to hear it is working :-)

If something should come up in your testing, please feel free to re-open this ticket.

Best regards,

Micahel

**Closed by michael-milette** 2020-05-27 17:23 UTC
Labels: bug
