### ISSUE TITLE
Feature request: {ifingroup}

### ISSUE THREAD

**Issue by cljkoopman** [michael-milette/moodle-filter_filtercodes#53] opened 2017-12-20 23:25 UTC
Hi Michael,

I would like to use the following tag: {ifmemberofgroup}.

A very nice application for this is the following:

With 'groupchoice' students can register themselves in certain Moodle groups.
On a 'personal' page they can then be given the personalized information that is based on those choices.

EXAMPLE
A student chooses (for example) the group 'physics'. For example, the ID of that group is 231.
On his personal page (a Moodle page) you will find the following text:

-----------------------------------
Hi {firstname},

Below is the information about the choices you have made.

{ifmemberofgroup 231}
You have opted for 'physics'. That is a good job that you have to work hard for. Etc.
{/ ifmemberofgroup}

{ifmemberofgroup 598}
You chose 'French language'. A good choice if you are willing to learn a lot of words. Etc.
{/ ifmemberofgroup}

{userpictureimg X}
Name: {fullname}
Username: {username}
--------------------------------------

Sincerely, Kees Koopman.

**Comment by jprovasnik** [comment] 2019-10-22 14:38
+ 1 (million) to this filter enhancement! 

We'd like to have a generic set of instructions in our student assignments followed by 4 different versions of the assignment instructions (that pertain to a specific group). Then students would see instructions that pertain to their group only see and everyone gets to submit into the same assignment module. 

Currently, we have four duplicated versions of every assignment in our class, each one grouped to one of our 4 groups so it can contain slightly different instructions. We have 85 total assignments in each of our courses, so times that by 4 duplicated variations for each and you can see why this method is a nightmare to manage. 

Since it's just the assignments instructions that are a little bit different for each group, we'd love a filter code that could help with this.

**Comment by jprovasnik** [comment] 2019-10-22 14:43
Perfect example is how the WebService filters a text area between the Moodle WebBrowser versus the Moodle App: https://moodle.org/plugins/filter_ws
<img width="1008" alt="filterws_editor" src="https://user-images.githubusercontent.com/44345287/67298140-d539b700-f4b8-11e9-9203-4bfe0e429a92.png">

**Comment by jprovasnik** [comment] 2019-10-22 15:03
And instead of having it filter by group 'name,' maybe it can filter by group 'ID' instead since groups can be assigned an ID number (if that makes things easier).

**Comment by tpil** [comment] 2020-04-12 19:06
Hello Michael,

I would appreciate it if you add the {ifmemberofgroup}. I would like to add some gamification features based on the group. Could you add the {mygroups} tag as well which will display a list with all the user's groups?

**Comment by michael-milette** [comment] 2020-04-14 04:59
Hi @tpil,

Thank you for taking the time to share your thoughts. It really helps me better understand how FilterCodes is used and how people would like to use it.
With regards to your proposal for a {mygroups} tag, I would ask you to do 2 things:

1. Create a separate ticket for it.
2. Describe in detail why and how you would use it.

This will help me better understand your need and therefore also how it should be implemented.

Best regards,

Michael

**Comment by michael-milette** [comment] 2020-10-09 10:14
Hello @tpil , @cljkoopman , @jprovasnik and @pablojavier !

I am please to let you know that a new set of {ifingroup id|idnumber}{/ifingroup} tags have been finally added to FilteCodes. The parameter can either be the group id (you can find that in the URL while editing) or a **Group ID number** that you can specify in the group's settings.

The new tags are currently only available on GitHub and is ready for testing. If you have a few minutes, please give it a try and let me know if it works for you. If it all works out, they will be included in the next release of FilterCodes on Moodle.org in the near future.

Best regards,

Michael Milette

**Closed by michael-milette** 2020-10-09 10:14 UTC
Labels: enhancement, hacktoberfest

**Comment by jprovasnik** [comment] 2020-10-09 11:48
Thanks! Im a bit new to this. Does this mean I click on "Code" tab in the navigation and then click the green Code button? or is that only for the latest release

**Comment by tpil** [comment] 2020-10-09 12:10
Thank you @michael-milette for adding this filter code. It can be used in many different ways. I can run some tests on our testing servers and see how it works. Is there anything else we must change except the actual folder of the plugin so it can work?

**Comment by jprovasnik** [comment] 2020-10-10 13:50
I have not had success yet. I'm on the latest 3.9 site fyi.
Here were my steps:
I've created 3 groups and assigned them an numerical ID. 
I've added myself into the course as a teacher, and placed myself in one of the three groups. 
I created an assignment and (hopefully correctly) set up the filter. AllI am seeing is the pipeline: 

<img width="484" alt="1 Create Group" src="https://user-images.githubusercontent.com/44345287/95656657-cdb25a00-0add-11eb-8fc5-199b38e337e6.png">
<img width="573" alt="2 Use Filter" src="https://user-images.githubusercontent.com/44345287/95656658-cdb25a00-0add-11eb-96b6-e09ff1da0e54.png">
<img width="314" alt="3 View Filter" src="https://user-images.githubusercontent.com/44345287/95656659-ce4af080-0add-11eb-8364-2001626ff4d4.png">

When I view, I only see the

**Comment by michael-milette** [comment] 2020-10-11 11:13
Hi @jprovasnik , 

Thank you for this great question. The pipe line means you should choose one option or the other. Try:

{ifingroup 1}
Your content for group A.
{/ifingroup}{ifingroup 2}
Your content for group B.
{/ifingroup}{ifingroup 3}
Your content for group C.
{/ifingroup}

Did You Know? The name of the field Group ID Number is misleading - it does not need to be a number. It can be a letter or even a word. So instead of 1, 2 and 3, you could set the Group ID Numbers to A, B and C. Then your FilterCodes would be:

{ifingroup A}
Your content for group A.
{/ifingroup}{ifingroup B}
Your content for group B.
{/ifingroup}{ifingroup C}
Your content for group C.
{/ifingroup}

I appreciate the feedback, the details on how to reproduce the issue the screenshots. I can see how it might be confusing. I will work on fixing that. Let me know if the corrected syntax works better for you.

Best regards,

Michael

**Comment by jprovasnik** [comment] 2020-10-11 13:16
Thanks - good insight. I've updated my "ID"  and now all works just as expected!
I do notice that admin and teacher roles must also be in the same groups to see the content. No complaints from me here, but I am anticipating that someone may bring this up as a future concern or enhancement. 
But for where we are now, this is exactly what I was looking for!

**Comment by michael-milette** [comment] 2020-10-14 04:21
Hi @jprovasnik ,

That is a good point. However, if a teacher wanted to test/preview what different groups would see, does it not make sense to have them add themselves to each of the different groups?

I would appreciate any further thoughts you might have on this.

Best regards,

Michael

**Comment by jprovasnik** [comment] 2020-10-14 11:42
What comes to mind are "admin" users (who generally won't be enrolled in course or course groups but may be asked to help troubleshoot teacher issues) and "TA"s (As in grading TAs in large schools, versus co-teaching TAs) who would be asked to help grade here and there throughout their department (who generally wouldn't enroll in a course or in a course group due to the sporadic nature of help some TAs provide). Those are the 2 scenarios I had in mind when I had made my last comment. Thanks,

**Comment by cljkoopman** [comment] 2020-10-14 12:18
Hi jprovasnik,

Is this a solution for the problem you write about: [https://moodle.org/plugins/block_demostudent](https://moodle.org/plugins/block_demostudent)

**Comment by michael-milette** [comment] 2020-10-14 15:11
Hi @jprovasnik 

Thanks for the scenarios and the link - much appreciated. It is great to hear how people set-up their site and use plugins for situations like this. :-)

Best regards,

Michael
