### ISSUE TITLE
Feature Request: Alternative to double braces

### ISSUE THREAD

**Issue by rschrenk** [michael-milette/moodle-filter_filtercodes#101] opened 2020-04-13 11:59 UTC
Hello,
in [filter.php approx in line 286](https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/filter.php#L286) you replace double brackets by characters produced with chr-Function.

After [line 1417](https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/filter.php#L1417) you restore them, but only as single brackets.

Is there a reason for this, or is it a bug?

Unfortunately because of this behaviour filtercodes is breaking other functionality, like from STACK-Questions, that depend on the double-brackets.

Greetings

**Comment by michael-milette** [comment] 2020-04-14 04:29
Actually it is working as designed and not wrongly.

I will need to look into this. It has been my experience that, in situations similar to this, the problem is the order in which the other plugin is executing its code. Any plugin that need to do its own filtering/substitution of content should always do so before calling Moodle's filtering for this very reason.

The other situation that I have seen happens when a developer processes user entered content before it is saved to the database instead of on output. Moodle itself even had one of these bugs for years in the way it was storing custom user fields. Fortunately that has since been corrected.

Moodle filtering should be applied as the very last step before output. Otherwise there is a strong possibility of the conflict you are experiencing.

**Comment by rschrenk** [comment] 2020-04-14 09:15
We are using the question type STACK, that outputs a certain syntax which is interpreted by MathJAX by JavaScript to display a formula as image. Therefore changing the order of filters does not work.

In many cases double brackets are used, like in the following example:

`\( {@n4@} \frac{{@z4@}}{{@n1@}}-{@n3@} \frac{{@z1@}}{{@n1@}} : {@n2@}\) = [[input:ans1]]  [[input:ans2]] [[validation:ans1]] [[validation:ans2]]`

In that case filter_filtercodes broke all our stack-questions. Therefore I adapted the filter-function accordingly to keep double brackets.

**Comment by michael-milette** [comment] 2020-04-16 06:57
Hi @rschrenk , thank you very much. You have made a very good point. I will need to give this scenario some consideration.

**Comment by michael-milette** [comment] 2020-05-16 21:17
Hi @rschrenk ,
I have been thinking about this problem. I can't just change the syntax of the escaped version of tags as there are probably many people who have already started using them.

However, I would consider adding a setting to FilterCodes to give you a choice of which syntax you want to use for escaped tags. By default, it would still use the {{ and }} syntax. However, for people in your situation, you would be able to go into the FilterCodes settings and change it to something else.

If I gave you a configurable option of selecting either {{ and }} OR {{{ and }}}, would that work for you? If so, I should be able to implement it in time for the next release of FilteCodes which will be coming out a few days before Moodle 3.9 next month.

Let me know what you think.

Best regards,

Michael

**Comment by rschrenk** [comment] 2020-05-17 08:58
Hello,

such a trigger in the website-administration would be sufficient in my case!

Kind regards

**Comment by michael-milette** [comment] 2020-05-24 18:33
Hi @rschrenk ,

A new setting has been added to FilterCodes which should allow you to decide whether you want to use {{ double }} or {{{ triple }}} braces for displaying FilterCode tags without being filtered. Selecting the triple option should resolve your conflicts with MathJAX. (the default is still double)

Please try it out and let me know how it works out for you. I would appreciate it if you could do this before the end of May in case I need to make any further changes.

For now, it is only available from the FilterCodes repository on GitHub so you will need to downloaded it from here. This new feature will be included in version on Moodle.org/plugins a few days before the launch of Moodle 3.9 in June 2020.

Best regards,

Michael

**Comment by rschrenk** [comment] 2020-05-25 06:48
Hello,

I tested your new setting, but I fear it will not work as expected.

First of all this approach has to be considered as a workaround, not a solution. It may produce further problems in the future. What if someone makes a course archive and transfers to another Moodle that has another setting chosen? Then the behavior changes, but the texts don't.

Furthermore, the 2-brackets and 3-brackets are meant as an "ignore"-flag. If I use this, I would expect that the text is not touched at all. But it is...

I entered the following text in a Moodle label:
`{{firstname}} {firstname} {{{firstname}}} {{{something_else}}}`

On the Moodle with the old plugin version, I get the following output:
`{firstname} Robert {{firstname}} {{something_else}}`

On the Moodle with the master-branch, I get the following output:
`{Robert} Robert {firstname} {something_else}`

So I think the new plugin made the problem even worse. No matter if I use 1, 2 or 3 brackets it ends up having only 1 bracket at the end. This would still break our MathJax-Output.

**A real solution must not modify the text at all.**

As filters can be disabled per course module (and even per course), wouldn't it be better not to provide such a functionality at all? If someone wants to write ABOUT filtercodes and show filtercodes, this person could disable the filter for a certain text at all.

It is really not a good behavior to modify texts of which you don't know if they are intended to work with your filter.

If you want to stick to the "ignore"-flag, then perhaps you should consider to modify the brackets to use another, unique syntax - e.g. {fc:firstname} or {filtercode:firstname}. Would be hard for users at the next update, but on the long run, it is maybe a better solution.

Thank you for your commitment in this matter!

Kind regards
Robert

**Comment by michael-milette** [comment] 2020-05-25 14:38
Hi Robert,

The only unexpected result in your test was that {{firstname}} ended up turning into {{Robert}}. I am sure this could be fixed. However changing the braces to [brackets] is not an option as it results in other issues. Trading one problem for another is not a solution and I am not ready to inconvenience my clients who all use this.

As this solution does not address your requirement, I will revert it back to its original behavior and place this issue in our backlog for further future consideration.

Best regards,

Michael

**Comment by michael-milette** [comment] 2020-05-25 16:36
Hi Robert,

It occurs to me that MathJAX should not be trying to process tags it does not understand and don't belong to it. I would therefore submit that this is actually a problem with MathJAX.

While I might be able to find a way to work around this, you will never be able to prevent people from typing content that includes braces. If that causes MathJAX problems too, then it really isn't a FilterCodes specific issue, wouldn't you agree?

Best regards,

Michael

**Comment by rschrenk** [comment] 2020-05-25 16:45
The problem is that filtercode actually **removes** brackets, also in situations, where it should not do it.

The problem is not that MathJAX tries to process something it does not understand, but that the MathJAX Syntax is broken because of missing brackets.

This is not a MathJAX-Issue, I fear. I don't know what would be best in that case, but the solution with three brackets unfortunately does not work in that case.

 How often do your current users use the double brackets? As long as I understood you only use it, if you want to show a filtercode without processing it (you want to ignore it). Is this a use case that is really used very very often?

Perhaps it would be a compromise if you change the syntax of the ignore-pattern. Like {fcignore:{firstname}} ? That way you would not upset your current users, as the syntax of the filtercodes themselves does not change.

I am sorry, that this is a complicated case ...

**Comment by michael-milette** [comment] 2020-05-25 17:25
Hi Robert,

You are right. I had forgotten that. For now, as my time to work on this is limited, I replaced the option to change the number of braces with an option to simply enable or disable the escaped braces. The default is to have the escaped braces option available however you can disable it which will leave all braces as they are.

Best regards,

Michael

**Comment by rschrenk** [comment] 2020-05-25 18:19
Hello,

yes, this would be ok, I tested and it worked.

Kind regards and thanks your your contribution!

**Comment by michael-milette** [comment] 2020-05-25 20:01
Hi Robert,

Could you do me a favour and try the latest FilterCodes from GitHub. Be sure to re-enable the escaped braces option. Let me know how it turns out for you as soon as you are done. I would prefer to keep this up as briefly as possible if it is not going to work out.

Michael

**Comment by rschrenk** [comment] 2020-05-26 04:51
Hi Michael,
I updated the code, went to the site administration and saved the setting again. Then checked the label from that course - it seemed to work. 
Kind regards

**Comment by michael-milette** [comment] 2020-05-26 04:57
Thanks Robert.

I changed the commented tags to [{tag}] which seems to have done the trick. I also left in the option to disable it completely in case it does cause someone trouble down the road. Hopefully it won't mess up too many people out there (and my clients of course).

I will update the documentation within the next few days (it is only in code right now) and post another update on GitHub.

Thank you for taking the time and effort to work through this issue with me.

Best regards,

Michael

**Closed by michael-milette** 2020-05-26 04:57 UTC
Labels: backlog, enhancement
